import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
let proc: ReturnType<typeof Bun.spawn>, upstream: ReturnType<typeof Bun.serve>, port=0, upstreamPort=0, base=""; const staticRoot=mkdtempSync(join(tmpdir(),"titen-dashboard-adapter-"));
const forwarded: Array<{authorization:string|null;body:Record<string,unknown>}>=[];
beforeAll(async()=>{ mkdirSync(`${staticRoot}/dashboard`,{recursive:true}); writeFileSync(`${staticRoot}/dashboard/index.html`,"DASHBOARD_OK"); try{symlinkSync("/etc/passwd",`${staticRoot}/passwd-link`)}catch{} upstream=Bun.serve({hostname:"127.0.0.1",port:0,async fetch(request){const path=new URL(request.url).pathname;if(path==="/healthz")return Response.json({data:{status:"ok"}});if(path==="/readyz")return Response.json({data:{ready:true}});if(path==="/v1/memory-views/compile"){const body=await request.json() as Record<string,unknown>;forwarded.push({authorization:request.headers.get("authorization"),body});return Response.json({data:{lens:body.lens,focus_id:body.focus_id??null,nodes:[],edges:[],metadata:{}}})}return new Response("Not found",{status:404})}}); upstreamPort=upstream.port; const reservation=Bun.serve({hostname:"127.0.0.1",port:0,fetch:()=>new Response("reserved")}); port=reservation.port; base=`http://127.0.0.1:${port}`; await reservation.stop(true); proc=Bun.spawn({cmd:[process.execPath,"scripts/dashboard-adapter.ts"],env:{...process.env,TITEN_DASHBOARD_LIVE:"true",TITEN_API_URL:`http://127.0.0.1:${upstreamPort}`,TITEN_API_KEY:"adapter-test-key",TITEN_DASHBOARD_PORT:String(port),TITEN_DASHBOARD_ORIGIN:"https://ra-tuf.example",TITEN_DASHBOARD_ROOT:staticRoot},stdout:"ignore",stderr:"pipe"}); for(let i=0;i<250;i++){try{if((await fetch(`${base}/dashboard`)).ok)return}catch{} await Bun.sleep(20)} throw new Error("adapter did not start")});
afterAll(()=>{proc?.kill();upstream?.stop(true);rmSync(staticRoot,{recursive:true,force:true})});
describe("dashboard adapter boundary",()=>{
 test("serves both dashboard routes with hardened headers",async()=>{for(const p of ["/dashboard","/dashboard/"]){const r=await fetch(base+p);expect(await r.text()).toBe("DASHBOARD_OK");const csp=r.headers.get("content-security-policy");expect(csp).toContain("connect-src 'self'");expect(csp).toContain("img-src 'self' data:")}});
 test("reports the configured live service",async()=>{expect(await(await fetch(base+"/dashboard-api/status")).json()).toEqual({mode:"live",endpoint:`127.0.0.1:${upstreamPort}`,authentication:"server",authenticated:true});expect((await fetch(base+"/dashboard-api/health")).status).toBe(200);expect((await fetch(base+"/dashboard-api/readiness")).status).toBe(200)});
 test("validates and forwards governance lenses",async()=>{const call=(body:Record<string,unknown>)=>fetch(base+"/dashboard-api/atlas/compile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});expect((await call({lens:"scope_preview",limit:50})).status).toBe(400);for(const body of [{lens:"scope_preview",focus_id:"principal_ops",limit:50},{lens:"knowledge_release",limit:25}])expect((await call(body)).status).toBe(200);expect(forwarded).toEqual([{authorization:"Bearer adapter-test-key",body:{lens:"scope_preview",focus_id:"principal_ops",limit:50}},{authorization:"Bearer adapter-test-key",body:{lens:"knowledge_release",limit:25}}])});
 for(const p of ["//etc/passwd","/%2fetc/passwd","/%252fetc/passwd","/../etc/passwd","/%2e%2e/etc/passwd","/%252e%252e/etc/passwd","/..%5cetc%5cpasswd","/%255c..%255cetc/passwd","/etc/passwd%00","/passwd-link"]) test(`blocks ${p}`,async()=>{const r=await fetch(base+p); const b=await r.text(); expect(r.status).not.toBe(200); expect(b).not.toContain("root:x:")});
 test("rejects foreign host and origin",async()=>{expect((await fetch(base+"/dashboard-api/status",{headers:{host:"evil.test"}})).status).toBe(403); expect((await fetch(base+"/dashboard-api/status",{headers:{origin:"https://evil.test"}})).status).toBe(403)});
 test("accepts only the configured reverse-proxy origin",async()=>{expect((await fetch(base+"/dashboard-api/status",{headers:{host:"ra-tuf.example",origin:"https://ra-tuf.example"}})).status).toBe(200);expect((await fetch(base+"/dashboard-api/status",{headers:{host:"ra-tuf.example",origin:"https://evil.test"}})).status).toBe(403)});
});
