import { first } from "./db";
import { notFound, validationError } from "./errors";
import type { RequestContext, Result } from "./http";
import { expireClaim, revokeClaim, supersedeClaim } from "./lifecycle";
import { LIMITS, requireObject, requireString } from "./validate";

type Row={id:string;project_id:string|null;actor_id:string;statement:string;confidence:number;trust:string;visibility:string;status:string;created_at:string;contradictions:number;sources:number};
const terminal=new Set(["superseded","expired","revoked"]);
function priority(r:Row,now:Date){const age=Math.floor((now.getTime()-new Date(r.created_at).getTime())/86400000);return (r.status==="disputed"?1000:0)+r.contradictions*100+Math.round((1-r.confidence)*100)+Math.min(90,Math.max(0,age));}
function deadline(r:Row){return new Date(new Date(r.created_at).getTime()+7*86400000).toISOString()}
function encode(v:string){return btoa(v)} function decode(v:string){try{return atob(v)}catch{throw validationError("Invalid cursor.")}}
async function visible(ctx:RequestContext,id:string){const p=ctx.principal!;const r=await first<Row>(ctx.app.db,`SELECT c.id,c.project_id,c.actor_id,c.statement,c.confidence,c.trust,c.visibility,c.status,c.created_at,COUNT(DISTINCT CASE WHEN s.relation='contradicts' THEN s.observation_id END) contradictions,COUNT(DISTINCT s.observation_id) sources FROM claims c LEFT JOIN claim_sources s ON s.claim_id=c.id WHERE c.id=? AND c.org_id=? AND (c.visibility!='private' OR c.actor_id=?) GROUP BY c.id`,[id,p.orgId,p.principalId]);if(!r)throw notFound();return r}
function item(r:Row,now:Date){const score=priority(r,now);return {queue_item_id:`review:${r.id}`,claim_id:r.id,status:terminal.has(r.status)?"resolved":"open",severity:score>=1100?"critical":score>=1000?"high":score>=150?"medium":"low",priority:score,owner:r.actor_id,next_action:r.status==="disputed"?"supersede, expire, or revoke after evidence review":"review low-confidence evidence",deadline:deadline(r),ttl_seconds:Math.max(0,Math.floor((new Date(deadline(r)).getTime()-now.getTime())/1000)),evidence:{claim_id:r.id,source_count:r.sources,contradiction_count:r.contradictions,statement:r.statement,trust:r.trust,confidence:r.confidence},audit:{record_type:"claim",record_id:r.id},terminal_state:terminal.has(r.status)?r.status:null}}
export async function listReviewerQueue(ctx:RequestContext):Promise<Result>{const p=ctx.principal!,now=ctx.app.now();const limit=Math.min(100,Math.max(1,Number(ctx.url.searchParams.get("limit")??25)||25));const project=ctx.url.searchParams.get("project_id"),status=ctx.url.searchParams.get("status")??"open",cursor=ctx.url.searchParams.get("cursor");const rows=await ctx.app.db.all<Row>(`SELECT c.id,c.project_id,c.actor_id,c.statement,c.confidence,c.trust,c.visibility,c.status,c.created_at,COUNT(DISTINCT CASE WHEN s.relation='contradicts' THEN s.observation_id END) contradictions,COUNT(DISTINCT s.observation_id) sources FROM claims c LEFT JOIN claim_sources s ON s.claim_id=c.id WHERE c.org_id=? AND (c.visibility!='private' OR c.actor_id=?)${project?" AND c.project_id=?":""} GROUP BY c.id`,project?[p.orgId,p.principalId,project]:[p.orgId,p.principalId]);let items=rows.map(r=>item(r,now)).filter(x=>status==="all"||(status==="open"?x.status==="open":x.terminal_state===status)).sort((a,b)=>b.priority-a.priority||a.deadline.localeCompare(b.deadline)||a.claim_id.localeCompare(b.claim_id));if(cursor){const [s,d,id]=decode(cursor).split("|");items=items.filter(x=>x.priority<Number(s)||(x.priority===Number(s)&&(x.deadline>d||(x.deadline===d&&x.claim_id>id))))}const page=items.slice(0,limit),last=page.at(-1);return {data:{queue:"reviewer",items:page},meta:{count:page.length,next_cursor:items.length>limit&&last?encode(`${last.priority}|${last.deadline}|${last.claim_id}`):null}}}
export async function actReviewerQueue(ctx:RequestContext):Promise<Result>{const id=ctx.params.id!;await visible(ctx,id);const b=requireObject(await ctx.json()),action=requireString(b,"action",32);if(!["supersede","expire","revoke"].includes(action))throw validationError("action must be supersede, expire, or revoke.");const payload:any={reason:typeof b.reason==="string"?b.reason:undefined};if(action==="supersede")payload.superseded_by=requireString(b,"superseded_by",LIMITS.identifier);const request=new Request(ctx.request.url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const delegated={...ctx,request,json:async()=>payload,rawBody:async()=>JSON.stringify(payload)};return action==="supersede"?supersedeClaim(delegated):action==="expire"?expireClaim(delegated):revokeClaim(delegated)}
